version: "3"
services:
  app:
    build: .
    container_name: app
    ports:
      - "8002:8002"
      - "11537:11537"
    depends_on:
      - db
    links:
      - db
    volumes:
      - .:/src
  db:
    image: postgres:12
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: oneteam
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    restart: always
    user: root
